language: java
sudo: true
script:
  - mvn install
  - bash scripts/surge_deploy.sh
before_deploy:
  - openssl aes-256-cbc -K $encrypted_fbf3aba49539_key -iv $encrypted_fbf3aba49539_iv
    -in .travis/deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - cp deploy_rsa ~/.ssh/deploy_rsa
  - chmod 600 ~/.ssh/deploy_rsa
  - ssh-add ~/.ssh/deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      repo: sef-global/sef-site
      branch: master
